permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: ww
  email: wangwei1665@126.com
  
# 站点信息
title: zero's space
description: My personal blog


# gavatar头像及Favicon
gavatar: /public/img/background/lulu.png
favicon: /public/img/background/lulu.png

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
