baseurl: ""
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis","tables", "fenced_code_blocks", "autolink","strikethrough", "superscript", "with_toc_data"]
safe: false
highlighter: pygments
excerpt_separator: "\n\n\n"
paginate: 5
sitemapurl: "http://zero1665.github.io"
