permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet #默认是 kramdown

# 作者信息
author: 
  name: ww
  email: wangwei1665@126.com
  
# 站点信息
title: zero's space
description: My personal space


# gavatar头像及Favicon
gavatar: /public/img/background/lulu.png
favicon: /public/img/background/lulu.png

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: zero1665

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

#site-wide 默认设置

defaults:
  -
    scope:
      path: "" #空字符串这里代表的是project里的所有文件
      type:    #指定应用到的类型，一般为"posts" "drafts" "pages"其中的一个
    values:
      layout:   #这是指定想要应用到上面path的布局文件，比如"default"
      author: "ww" #指定作者


